# Generated by Django 5.2.8 on 2026-01-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='bg_color',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
