# Generated by Django 5.2.8 on 2026-01-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_wardrobe_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobe',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardrobe',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
